CREATE TABLE user(
	userID			INT			NOT NULL AUTO_INCREMENT,
	userName		CHAR(30)	NOT NULL,
	firstName		CHAR(30)	NOT NULL,
	lastName		CHAR(30)	NOT NULL,
	password		VARBINARY	NOT NULL,
	email			VARCHAR		NOT NULL,
	email-active	BOOLEAN		NULL,
	timeZone		CHAR(10)	NOT NULL,
	temp-pass		VARBINARY	NULL,
		CONSTRAINT USER_PK PRIMARY KEY(userID)
);

CREATE TABLE type(
	userID			INT			NOT NULL,
	typeID			INT			NOT NULL AUTO_INCREMENT,
	ul-Lat			FLOAT		NULL,
	ul-Long			FLOAT		NULL,
	lr-Lat			FLOAT		NULL,
	lr-Long			FLOAT		NULL,
	speed			INT			NOT NULL,
	objectType		CHAR(100)	NOT NULL,
	pic				VARCHAR		NOT NULL,
		CONSTRAINT TYPE_PK PRIMARY KEY(typeID),
		CONSTRAINT USER_TYPE_FK FOREIGN KEY(userID)
			REFERENCES USER(userID)
			ON UPDATE CASCADE
);

CREATE TABLE tracked(
	trackedID		INT			NOT NULL AUTO_INCREMENT,
	typeID			INT			NOT NULL,
	licenceNumber	CHAR(10)	NULL,
	make			CHAR(30)	NULL,
	model			CHAR(30)	NULL,
	year			CHAR(10)	NOT NULL,
	pic				VARCHAR		NOT NULL,
	sex				CHAR(10)	NULL,
	tagNumber		CHAR(20)	NOT NULL,
	password		VARBINARY	NOT NULL,
		CONSTRAINT TRACKED_PK PRIMARY KEY(trackedID),
		CONSTRAINT TYP_TRACK_FK FOREIGN KEY(typeID)
			REFERENCES TYPE(typeID)
			ON UPDATE CASCADE
);

CREATE TABLE location(
	locationID		INT			NOT NULL AUTO_INCREMENT,
	trackedID		INT			NOT NULL,
	date			DATETIME	NOT NULL,
	health			VARCHAR		NULL,
	lat				FLOAT		NULL,
	long			FLOAT		NULL,
		CONSTRAINT LOCATION_PK PRIMARY KEY(locationID),
		CONSTRAINT TRAC_LOC_FK FOREIGN KEY(trackedID)
			REFERENCES TRACKED(trackedID)
			ON UPDATE CASCADE
); 
	